export const categories = [
  "All Products",
  "LOVE&SEX",
  "BREAK WITCHCRAFT",
  "Money & Success.",
  "Cleansing & Healing.",
  "Miscellaneous",
  "Dark Magic",
];

export const products = [
  {
    id: 1,
    name: "Bend At My Feet. (Dominate) Perfume Oil.",
    price: "$14.44",
    img: "/images/product1.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 2,
    name: "Binding Oil.",
    price: "$5.55",
    img: "/images/product2.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 3,
    name: "Reconciliation Oil (Almost all our oils come dressed, as in picture.)",
    price: "$5.55",
    img: "/images/product3.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 4,
    name: "You Are Mine ONLY Mine perfume/spray.",
    oldPrice: "$14.00",
    price: "$12.00",
    sale: true,
    img: "/images/product3.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 5,
    name: "Pink Sweetening Honey W/ Rose Quartz.",
    oldPrice: "$12.99",
    price: "$10.10",
    sale: true,
    img: "/images/product6.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 6,
    name: "Love Extract Oil : Sexual Attraction with Pheromone's.",
    oldPrice: "$11.11",
    price: "$9.99",
    sale: true,
    img: "/images/product7.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 7,
    name: "Garrapata AKA: Tick Extract.",
    oldPrice: "$15.99",
    price: "$11.00",
    sale: true,
    img: "/images/product8.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 8,
    name: "Aphrodite Musk.",
    oldPrice: "$15.00",
    price: "$11.99",
    sale: true,
    img: "/images/product9.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 9,
    name: "Everything that's yours, is mine $. AKA: SPOIL ME OIL SPRAY!",
    oldPrice: "$16.99",
    price: "$12.99",
    sale: true,
    img: "/images/product10.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 10,
    name: "Come To Me 7 Day Candle.",
    oldPrice: "$12.99",
    price: "$10.50",
    sale: true,
    img: "/images/product11.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 11,
    name: "Sexual Creme.",
    oldPrice: "$12.00",
    price: "$9.99",
    sale: true,
    img: "/images/product12.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 12,
    name: "Sex And Love OIL.",
    oldPrice: "$18.99",
    price: "$14.99",
    sale: true,
    img: "/images/product13.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 13,
    name: "Love Extract Oil : Honey Love.",
    oldPrice: "$11.11",
    price: "$9.50",
    sale: true,
    img: "/images/product14.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 14,
    name: "LEGITIMATE PHERMONES! MOLECULA BIOLOGICA - YOUR PERSONAL SCENT. (Read description.)",
    oldPrice: "$18.00",
    price: "$12.99",
    sale: true,
    img: "/images/15.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 15,
    name: "Sex Only With Me Spray/Perfume.",
    price: "$12.99",
    img: "/images/16.jpg",
    category: "LOVE&SEX",
  },
    {
    id: 16,
    name: "Skull Candles.",
    price: "$7.77",
    sale: true,
    img: "/images/17.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 17,
    name: "Cinnamon Attraction Soap (Attract money or love, etc).",
    oldPrice: "$10.00",
    price: "$8.88",
    sale: true,
    img: "/images/18.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 18,
    name: "Real Heart Shaped Candle. - LIMITED EDITION (ONE LEFT).",
    price: "$16.99",
    sale: true,
    img: "/images/19.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 19,
    name: "Penis Candles (Dark or Light Work).",
    oldPrice: "$12.50",
    price: "$9.99",
    sale: true,
    img: "/images/20.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 20,
    name: "Sexual Attraction Perfume (Gender Neutral).",
    oldPrice: "$15.00",
    price: "$12.12",
    sale: true,
    img: "/images/21.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 21,
    name: 'Sex ONLY With Me Perfume (Gender Neutral).',
    oldPrice: "$15.00",
    price: "$11.99",
    sale: true,
    img: "/images/22.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 22,
    name: "Miel De Amor AKA: Honey Of Love.",
    price: "$5.55",
    img: "/images/23.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 23,
    name: "Do My Will Bath/Cologne.",
    oldPrice: "$9.99",
    price: "$7.77",
    sale: true,
    img: "/images/24.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 24,
    name: "Woman's Milk Multi-Use (Lotion, Bath, or Spell Ingredient).",
    oldPrice: "$20.99",
    price: "$14.99",
    sale: true,
    img: "/images/25.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 25,
    name: "Love Extract Oil: Sweet Sugar.",
    oldPrice: "$11.11",
    price: "$8.88",
    sale: true,
    img: "/images/26.jpeg",
    category: "LOVE&SEX",
  },
  {
    id: 26,
    name: "Perfume with Added Pheromones (Gender Fluid).",
    oldPrice: "$20.00",
    price: "$18.99",
    sale: true,
    img: "/images/27.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 27,
    name: "Bind Your Woman 7 Day Ritual (Lesbian or Man-to-Woman).",
    oldPrice: "$35.00",
    price: "$23.99",
    sale: true,
    img: "/images/28.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 28,
    name: "Men’s Specific Pheromone Spray.",
    oldPrice: "$9.99",
    price: "$4.99",
    sale: true,
    img: "/images/29.jpg",
    category: "LOVE&SEX",
  },
  {
    id: 29,
    name: "7 Wick Strong Tower Candle (Love, Attraction, Reconciliation, Domination).",
    price: "$15.00",
    img: "/images/30.jpeg",
    category: "LOVE&SEX",
  },
    {
    id: 30,
    name: "Break Witchcraft Oil.",
    oldPrice: "$17.00",
    price: "$14.99",
    sale: true,
    img: "/images/product31.jpeg",
    category: "BREAK WITCHCRAFT",
  },
  {
    id: 31,
    name: "SOAP: Remove Witchcraft, Bad Energy, &/or Mal De Ojo.",
    oldPrice: "$14.00",
    price: "$12.99",
    sale: true,
    img: "/images/product32.jpeg",
    category: "BREAK WITCHCRAFT",
  },
  {
    id: 32,
    name: "Expells Witchcraft.",
    oldPrice: "$15.99",
    price: "$11.99",
    sale: true,
    img: "/images/product33.jpeg",
    category: "BREAK WITCHCRAFT",
  },
  {
    id: 33,
    name: "Break Up Candle.",
    oldPrice: "$12.99",
    price: "$10.10",
    sale: true,
    img: "/images/product34.jpg",
    category: "BREAK WITCHCRAFT",
  },
  {
    id: 34,
    name: "7 Wick Tower Candle: Break Witchcraft.",
    oldPrice: "$17.00",
    price: "$14.00",
    sale: true,
    img: "/images/product35.jpg",
    category: "BREAK WITCHCRAFT",
  },
  {
    id: 35,
    name: "Hex Remover Oil.",
    oldPrice: "$6.00",
    price: "$4.44",
    sale: true,
    img: "/images/product36.jpg",
    category: "BREAK WITCHCRAFT",
  },
    {
    id: 40,
    name: "True Abundance, Money, & Success Oil Spray.",
    oldPrice: "$17.00",
    price: "$14.00",
    sale: true,
    img: "/images/pro37.jpg",
    category: "Money & Success.",
  },
  {
    id: 41,
    name: "Doble Suerte AKA Double My Luck Oil.",
    oldPrice: "$12.00",
    price: "$10.00",
    sale: true,
    img: "/images/pro38.jpeg",
    category: "Money & Success.",
  },
  {
    id: 42,
    name: "Cinnamon Attraction Soap (Attract money or love, etc)",
    oldPrice: "$10.00",
    price: "$8.88",
    sale: true,
    img: "/images/pro39.jpg",
    category: "Money & Success.",
  },
  {
    id: 43,
    name: "Money Attracting Soap.",
    price: "$11.11",
    img: "/images/pro40.jpeg",
     sale: true,
    category: "Money & Success.",
  },
  {
    id: 44,
    name: "Lucky Cash Bhudda Oil Spray.",
    oldPrice: "$15.00",
    price: "$13.00",
    sale: true,
    img: "/images/pro41.jpg",
    category: "Money & Success.",
  },
  {
    id: 45,
    name: "7 Day Money Drawing Candle.",
    oldPrice: "$15.00",
    price: "$9.99",
    sale: true,
    img: "/images/pro42.jpeg",
    category: "Money & Success.",
  },
  {
    id: 46,
    name: "Road Opener.",
    price: "$8.88",
     sale: true,
    img: "/images/pro43.jpg",
    category: "Money & Success.",
  },
  {
    id: 47,
    name: "Remove Money Blockages, To Bring Fast Money - Spiritual Bath.",
    oldPrice: "$7.77",
    price: "$7.77",
    sale: true,
    img: "/images/pro44.jpg",
    category: "Money & Success.",
  },
  {
    id: 48,
    name: "7 Wick Strong Tower Candle: Money & Abundance.",
    oldPrice: "$16.99",
    price: "$14.00",
    sale: true,
    img: "/images/pro45.jpg",
    category: "Money & Success.",
  },
  {
    id: 49,
    name: "Money Drawing 7 Day Candle.",
    price: "$15.00",
    img: "/images/pro46.jpeg",
    category: "Money & Success.",
  },
    {
    id: 50,
    name: "Real Heart Shaped Candle. - ONE LEFT",
    oldPrice: "$16.99",
    price: "$16.99",
     sale: true,
    sale: true,
    img: "/images/19.jpeg",
    category: "Cleansing & Healing.",
  },
  {
    id: 51,
    name: "Break Witchcraft Oil.",
    oldPrice: "$17.00",
    price: "$14.99",
    sale: true,
    img: "/images/product31.jpeg",
    category: "Cleansing & Healing.",
  },
  {
    id: 52,
    name: "SOAP : Remove Witchcraft, Bad Energy, &/or Mal De Ojo.",
    oldPrice: "$14.00",
    price: "$12.99",
    sale: true,
    img: "/images/product32.jpeg",
    category: "Cleansing & Healing.",
  },
  {
    id: 53,
    name: "Florida Water Soap.",
    oldPrice: "$6.50",
    price: "$5.55",
    sale: true,
    img: "/images/pro47.jpg",
    category: "Cleansing & Healing.",
  },
  {
    id: 54,
    name: "Healing Self Love Bath Salt Mix.",
    oldPrice: "$7.00",
    price: "$5.00",
    sale: true,
    img: "/images/pro48.jpg",
    category: "Cleansing & Healing.",
  },
  {
    id: 55,
    name: "Road Opener.",
    price: "$8.88",
    img: "/images/pro49.jpg",
    category: "Cleansing & Healing.",
  },
  {
    id: 56,
    name: "Rue Soap.",
    price: "$5.55",
    img: "/images/pro50.jpeg",
    category: "Cleansing & Healing.",
  },
  {
    id: 57,
    name: "Remove Blockages Bath.",
    price: "$7.77",
    img: "images/pro51.jpg",
    category: "Cleansing & Healing.",
  },
    {
    id: 70,
    name: "Reconciliation Oil (Almost all our oils come dressed, as in picture.)",
    oldPrice: "$6.00",
    price: "$5.55",
    sale: true,
    img: "images/product3.jpg",
    category: "Miscellaneous",
  },
  {
    id: 71,
    name: "Hexing Oil For Hexes, Break Up Spells, Justice Workings, or Wards.",
    oldPrice: "$16.00",
    price: "$12.99",
    sale: true,
    img: "/images/52.jpeg",
    category: "Miscellaneous",
  },
  {
    id: 72,
    name: "Skull Candles.",
    price: "$7.77",
    // st: true,
    sale: true,
    img: "/images/17.jpg",
    category: "Miscellaneous",
  },
  {
    id: 73,
    name: "Cinnamon Attraction Soap (Attract money or love, etc)",
    oldPrice: "$10.00",
    price: "$8.88",
    sale: true,
    img: "/images/18.jpg",
    category: "Miscellaneous",
  },
  {
    id: 74,
    name: "Honey Soap.",
    oldPrice: "$17.00",
    price: "$14.00",
    sale: true,
    img: "/images/53.jpg",
    category: "Miscellaneous",
  },
  {
    id: 75,
    name: "Magnet shreds/pieces, for dressing candles or jar work, etc.",
    oldPrice: "$10.99",
    price: "$8.99",
    sale: true,
    img: "/images/54.jpg",
    category: "Miscellaneous",
  },
  {
    id: 76,
    name: "7 Wick Strong Rainbow Candle MULTI USE READ DESCRIPTION.",
    oldPrice: "$19.99",
    price: "$16.99",
    img: "/images/55.jpg",
    category: "Miscellaneous",
  },
  {
    id: 77,
    name: "Road Opener.",
    price: "$8.88",
    img: "/images/56.jpg",
    category: "Miscellaneous",
  },
  {
    id: 78,
    name: "Do My Will, Bath/Cologne.",
    price: "$9.99",
    img: "/images/57.jpg",
    category: "Miscellaneous",
  },
  {
    id: 79,
    name: "Come Back To Me Oil",
    price: "$4.44",
    status: "Out of Stock",
    img: "/products/misc10.jpg",
    category: "Miscellaneous",
  },
  {
    id: 80,
    name: "Remove Blockages Bath.",
    price: "$7.77",
    img: "/images/pro51.jpg",
    category: "Miscellaneous",
  },
    {
    id: 90,
    name: "Hexing Oil For Hexes, Break Up Spells, Justice Workings, or Wards.",
    oldPrice: "$16.00",
    price: "$12.99",
    sale: true,
    img: "/images/52.jpeg",
    category: "Dark Magic",
  },
  {
    id: 91,
    name: "Skull Candles.",
    price: "$7.77",
    sale: true,
    img: "/images/17.jpg",
    category: "Dark Magic",
  },
  {
    id: 92,
    name: "Devour All Candle.",
    price: "$10.10",
    img: "/images/60.jpeg",
    category: "Dark Magic",
  },
  {
    id: 93,
    name: "Penis Candles, dark or light work.",
    price: "$12.50",
    img: "/images/20.jpg",
    category: "Dark Magic",
  },
  {
    id: 94,
    name: "Break Up Candle.",
    oldPrice: "$12.99",
    price: "$10.10",
    sale: true,
    img: "/images/product34.jpg",
    category: "Dark Magic",
  },
  {
    id: 95,
    name: "Large Breakup/Separation Candle.",
    oldPrice: "$15.99",
    price: "$14.00",
    img: "/images/61.jpeg",
    category: "Dark Magic",
  },
];
